add video player
htmlacademy-react/1955797-what-to-watch-10 pull request #6
Opened 2022-08-02 11:43 UTC by semenbushmanov

Добавил проигрывание видео при наведении курсора на карточку фильма.

2022-08-02 14:08 UTC, MrMeison requested changes

2022-08-02 14:08 UTC, MrMeison commented on project/src/components/film-card-list/film-card-list.tsx
> +  const [ ActiveFilmCard, setActiveFilmCard ] = useState<number|undefined>();
```suggestion
  const [ activeFilmCard, setActiveFilmCard ] = useState<number|undefined>();
```

2022-08-02 14:08 UTC, MrMeison commented on project/src/components/film-card/film-card.tsx
> +      onMouseEnter={() => handleMouseEnter()}
```suggestion
      onMouseEnter={handleMouseEnter}
```

2022-08-02 14:08 UTC, MrMeison commented on project/src/components/video-player/video-player.tsx
> +      videoRef.current.play();
а как сбрасывать воспроизведение?

2022-08-03 10:30 UTC, semenbushmanov commented
Исправил проблемы, связанные с не прекращением проигрывания видео при многократном перемещении мышки с карточки на карточку, перенеся всю логику в компонент film-card. В видеоплейере сделал остановку видео и возвращению к постеру (к сожалению кроме load() ничего не возвращает плейер к постеру: временные метки, установленные на 0 приводят к показу первого фрейма видео; других методов сделать сброс воспроизведения не нашел). Сейчас все работает, как требуется.

2022-08-04 08:11 UTC, merged